### ISSUE TITLE
Error setting up entry for duke energy gateway

### ISSUE THREAD

**Issue by nahte10** [mjmeli/ha-duke-energy-gateway#103]
hey there, I just moved into my apartment and was hoping to setup energy monitoring in home assistant but I get this error.  I am able to see the energy usage data on my duke app but not until the day is over so I might not have access to my live data. is there anyway I can contact duke to enable this?

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/duke_energy_gateway/__init__.py", line 54, in async_setup_entry
    selected_meter, selected_gateway = await client.select_default_meter()
  File "/usr/local/lib/python3.9/site-packages/pyduke_energy/client.py", line 175, in select_default_meter
    raise DukeEnergyError(
pyduke_energy.errors.DukeEnergyError: Failed to identify any smart meter with gateway access on your account`

**Comment by mjmeli** [comment]
This integration only works with the gateway which provides real time data. The gateway was given out as a pilot program and I'm not sure if you can get one anymore.

Theoretically without one, the integration could still function and provide yesterday's usage, but Home Assistant doesn't have a way to back-date data so it wouldn't be usable in the energy dashboard, which is really the intention of this integration. I didn't see much practical use for it so I didn't build it and don't really have plans to.
