### ISSUE TITLE
HA error logs.

### ISSUE THREAD

**Issue by shthfuup** [mjmeli/ha-duke-energy-gateway#18]
![Capture](https://user-images.githubusercontent.com/88147311/134211768-0dce9e38-2954-46b5-bf58-149134c1f809.JPG)

This error originated from a custom integration.

Logger: custom_components.duke_energy_gateway
Source: custom_components/duke_energy_gateway/__init__.py:107
Integration: Duke Energy Gateway (documentation, issues)
First occurred: 12:06:23 PM (1 occurrences)
Last logged: 12:06:23 PM

Could not identify a smart meter on your account with gateway access.

I configured the gateway earlier today and it is showing in the app as configured and online. I am able to access data real time via the Duke Energy app.

![Screenshot_20210921-124255_Duke Energy](https://user-images.githubusercontent.com/88147311/134213073-1786170f-eba6-4948-927a-073d716b90e5.jpg)

Note: When logging into the Duke Energy website; I see an old account (no longer active) along with the existing one that is in use and connected to the gateway.

Any advice on how I may be able to resolve this?
Thank you so much for all your efforts on this project!!

**Comment by shthfuup** [comment]
Thank you for replying so quickly. Here are my versions for both HACs and HA.
![HACS_Version](https://user-images.githubusercontent.com/88147311/134222756-783b7131-186d-4c83-8e05-905c5a14b186.JPG)

![HA_Versions](https://user-images.githubusercontent.com/88147311/134222766-253e0b32-ad27-40f1-b9f6-820c996f2a51.JPG)

I added the logging code you provided and here's that output...
https://pastebin.com/QPeNuaVh

**Comment by mjmeli** [comment]
Thanks, that's really helpful. I see the issue and I'll fix it today and get a new version pushed to HACS.

**Comment by mjmeli** [comment]
I just released a new version v0.0.10. You can get the update by refreshing info in HACS and then restarting HA. 
![image](https://user-images.githubusercontent.com/6422129/134232256-fd7297fb-7f2d-4eff-927c-f546bf399494.png)

I believe this should fix your issue but I don't have the exact scenario so I can't test it myself.

**Comment by shthfuup** [comment]
Thank you Mike! It fixed it perfectly, once updated, a new entity showed up.

Your talents are exceptional - thank you again,
Douglas
