### ISSUE TITLE
Unable to Find Integration After adding in HACS

### ISSUE THREAD

**Issue by highaltidude** [mjmeli/ha-duke-energy-gateway#63]
Version 0,1,0

## Describe the bug

I added the integregration per the instructions in the readme and after restart when I go to add integreation it is not showing in the list. I see it in the custom_components folder.

**Comment by mjmeli** [comment]
Make sure you do a hard refresh that clears cache on the integrations page. Ctrl+F5 on most browsers.

**Comment by highaltidude** [comment]
/facepalm Now I remember reading that somewhere. Appreciate the help. Works now
