### ISSUE TITLE
sensor.duke_energy_usage_today_kwh >>> Not Working

### ISSUE THREAD

**Issue by tteck** [mjmeli/ha-duke-energy-gateway#71]
It hasn't been reporting since around 3 pm est. according to HA's energy dashboard 
No errors in log
`sensor.duke_energy_current_usage_w` is working

**Comment by mjmeli** [comment]
Mine hasn't stopped reporting here. I'm surprised this one would give out because it just makes a new REST call every 60 seconds. Have you tried restarting your HA instance in case something got in a bad state?

**Comment by tteck** [comment]
It must be my gateway!? I've reset everything. Even on my phone it's not updating 1hr, 15min, usage

**Comment by apercrcl01** [comment]
I have the exact same issue

**Comment by apercrcl01** [comment]
Trying to restart gateway now. HA restart didn’t help.

**Comment by apercrcl01** [comment]
Got it working again after restarting and pairing the gateway.

**Comment by tteck** [comment]
What do you mean by pairing?

**Comment by apercrcl01** [comment]
Most of the time when I pull the power on the gateway I have to re-pair the meter to the gateway. The app usually prompts me for it but you can go in the smart meter information in the app and choose pair gateway if it’s not already connected.

**Comment by apercrcl01** [comment]
But now I appear to have lost the current energy sensor.

**Comment by tteck** [comment]
Had to push the reset next to the Ethernet port, repair to the meter and all's well now, including the current usage sensor.

**Comment by tteck** [comment]
![Screenshot 2022-02-25 6 14 00 PM](https://user-images.githubusercontent.com/21342670/155815502-759e2aad-1982-4416-922c-ada514c0c8cd.png)
Looks like the decimal point moved?

**Comment by lshep5801** [comment]
I have dual setup on different docker servers.
Two HA (V2022.2.6 & 2021.12.4) instances.
Two physical locations with two different meters.
They both have gone offline, one late 2/24/22 at 15:28 and the other on 2/25/22 around 03:00.  I have not done any troubleshooting yet.  Holding stable to see if any more forensic data is needed.

Attached are highlights of the log file.
[duke-errors-20220228.txt](https://github.com/mjmeli/ha-duke-energy-gateway/files/8156640/duke-errors-20220228.txt)

**Comment by apercrcl01** [comment]
After a couple more HA restarts and Duke Energy app force closes and now both sensors are working.

**Comment by mjmeli** [comment]
Since this appears to be a Duke API/gateway problem that also happens on the app, has anyone contacted Duke about it?
